// Code generated by "stringer -type=color"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Color0-0]
	_ = x[Color1-1]
	_ = x[Color2-2]
	_ = x[Color3-3]
	_ = x[Color4-4]
	_ = x[Color5-5]
	_ = x[Color6-6]
	_ = x[Color7-7]
	_ = x[Color8-8]
	_ = x[Color9-9]
	_ = x[Color10-10]
	_ = x[Color11-11]
	_ = x[Color12-12]
	_ = x[Color13-13]
	_ = x[Color14-14]
	_ = x[Color15-15]
}

const _color_name = "Color0Color1Color2Color3Color4Color5Color6Color7Color8Color9Color10Color11Color12Color13Color14Color15"

var _color_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 67, 74, 81, 88, 95, 102}

func (i color) String() string {
	if i >= color(len(_color_index)-1) {
		return "color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _color_name[_color_index[i]:_color_index[i+1]]
}
